# A Project to Guess the number generated by user
#(A course on Python projects by @Kyle_ying source:(Youtube))
"""
Created by @Hrishikesh_Salunkhe
"""

#Import random module to generate a random number 
import random

#Define a function to guess the number
def computer_num(x):
    minimum = 1
    maximum = x
    feedback = ""
    while (feedback != 'c' and maximum != minimum ):
        
        if(minimum != maximum):
            guess_num = random.randint(minimum, maximum)
        else:
            guess= minimum
        feedback = input(f"Is {guess_num} too High(h), too Low (l) or Correct (c) ").lower()
        if feedback =='h':
            maximum = guess_num -1
        elif feedback == "l":
            minimum = guess_num +1
    print("Your guess is Right")
    
number = int(input("Enter a number to guess"))
computer_num(number)